config/routes.rb
Kauppalista::Application.routes.draw do

  get "api_user_requests/index"

  get "api_user_requests/accept"

  get "api_user_requests/deny"

  get "api_user/create"

  get "home/index"

  resources :users
  match "signup" => "users#new"
  match "login" => "sessions#login"
  match "logout" => "sessions#logout"
  post "sessions/login_attempt"

  get 'lists/clean'
  resources :lists

  resources :items

  get 'api_users/create'
  get 'api_users/index'
  match 'api_users/:api_user_id/request_access' => 'api_users#request_user_access', :via => :get

  match 'requests' => 'api_user_requests#index'
  match 'requests/:id/accept' => 'api_user_requests#accept'
  match 'requests/:id/deny' => 'api_user_requests#deny'

  root :to => 'home#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name

  belongs_to :user
  has_many :items

  validates :name, :user_id, :presence => true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :auth_user_according_to_format
  before_filter :auth_user_for_this_list, :only => [ 'show', 'destroy' ]

  def auth_user_for_this_list
  	list = List.find params[ :id ]

  	unless list.user_id == @current_user.id
  		respond_to do |format|
  			format.html {
  				flash[ :error ] = 'Trying to access list without authorization'
    			redirect_to '/lists'
    		}
    		format.xml { render :xml => xml_error( 'unauthorized access to list' ) }
    	end
    else
    	@list = list
    end

  end

  def index
  	@lists = @current_user.lists
    respond_to do |format|
        format.html 
        format.xml { render :xml => @lists }
    end
  end

  def show
	 @items = @list.items
  
  	respond_to do |format| 
    	format.html {
    		if params[ :partial ]
    			render :partial => 'lists/list'
    		end
    	}
    	format.xml {
        render :xml => @items 
      }
  	end
  end

  def create
  	list = List.new( params[ :list ] )
  	list.user_id = @current_user.id
  	if list.save
  		flash[ :notice ] = 'Succesfully create new list'
  		redirect_to '/lists/' + list.id.to_s
  	else
  		flash[ :error ] = 'Creation failed'
  		render 'lists/new'
  	end
  end

  def new
  	@list = List.new
  end

  def destroy
  	@list.destroy
  	redirect_to lists_path
  end

  def clean
  	for list in List.all
  		unless list.user_id
  			list.destroy
  		end
  	end 
  	redirect_to '/'
  end
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list.html.erb
<ul id="items">
	<form>
	<% @items.each do |item| %>
		<li data-id="<%= item.id %>">
			<input class="check" type="checkbox">
			<span><%= item.name %><%= item.amount.strip != "" ? ', ' + item.amount : '' %></span>
			<input type="button" class="delete-item" value="X">
		</li>
	<% end %>
	<form>
</ul>

app/views/lists/_lists.html.erb
<ul id="all-lists">
<% for list in @lists %>
	<li><%= link_to list.name, list %><%=  %></a></li>
<% end %>
</ul>

app/views/lists/index.html.erb
<span class="new-list"><%= link_to 'New list', new_list_path %></span>
<%= render :partial => "lists" %>

app/views/lists/new.html.erb
<h1>New list for <%= @current_user.name %></h1>
<%= form_for @list, :url => url_for( :controller => 'lists', :action => 'create' ) do |list_form| %>
	<div class="create-list-field">
		Name for the list:
		<div><%= list_form.text_field :name %></div>
	</div>
	<div>
		<%= list_form.submit 'Create' %>
		<%= link_to 'Cancel', lists_path, :class => 'cancel' %>
	</div>
<% end %>

app/views/lists/show.html.erb
<% content_for :head_additional do %>
	<script type="text/javascript">
		$(document).ready( function () {
			listPageReady();
		} );
	</script>
<% end %>

<span><%= link_to '<- Back to lists', lists_path %></span> 

<div class="list-head">
	<h1>List, <%= @list.name %></h1>
	<span><%= link_to 'Remove', @list, :method => 'delete', :confirm => 'Do you really want to remove list ' + @list.name %></span>
</div>

<div id="list" data-list="<%= @list.id %>">
	<%= render :partial => 'lists/list' %>
</div>

<div id="status">&nbsp;</div>
<input id="add-new" type="button" value="Add">
<input id="remove-checked" type="button" value="Remove checked">

<div class="form" id="form">
</div>